
import { useState } from 'react'
import { MapContainer, TileLayer, useMapEvents, Marker, Popup } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import { RastiMarker } from './Icons'
const TrackPoints = () => {
  const [positions, setPositions] = useState([])
  const map = useMapEvents({
    click (e) {
      console.log(e)
      setPositions([...positions, e.latlng])
      map.locate()
    },
    locationfound (e) {
      // use another marker for current location
      map.flyTo(e.latlng, map.getZoom())
    }
  })
  return (
    <>
      {positions.map((position) => <RastiMarker position={position} />)}
    </>
  )
}

const DesignMap = () => {
  if (typeof window === 'undefined') {
    return null
  }

  console.log(process.env, 'd')
  // const mapUrl = process.env.TAMPERE_MAP_URL
  const mapUrl = 'http://localhost:5000/tampere/{z}/{x}/{y}.png'
  // const mapUrl = 'https://xn--hyty-6qa.net/omarasti/{z}/{x}/{y}.png'
  console.log(mapUrl)
  return (
    <MapContainer
      style={{ width: '100%', height: '80vh' }} center={[52.12076638441093, 2.982406743276816]} zoom={14.5}
    >
      <TileLayer
        url={mapUrl}
        attribution='Generated by TilesXYZ'
      />
      <TrackPoints />
    </MapContainer>
  )
}

export default DesignMap
