
import { MapContainer, TileLayer } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'

const DesignMap = () => {
  if (typeof window === 'undefined') {
    return null
  }
  // const mapUrl = process.env.TAMPERE_MAP_URL
  // const mapUrl = 'http://localhost:5000/tampere/{z}/{x}/{y}.png'
  const mapUrl = 'https://xn--hyty-6qa.net/omarasti/{z}/{x}/{y}.png'
  console.log(mapUrl)
  return (
    <MapContainer style={{ width: '100%', height: '80vh' }} center={[52.12076638441093, 2.982406743276816]} zoom={14.5}>
      <TileLayer
        url={mapUrl}
        attribution='Generated by TilesXYZ'
      />

    </MapContainer>
  )
}

export default DesignMap
