version: '3'
services:
  nginx:
    image: nginx:1.28-alpine
    container_name: omarasti_data
    volumes:
    - ./html:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - 8888:80
